spring:
  profiles:
    active: local
  application:
    name: my-bank-demo-app
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
  show-actuator: false

server:
  port: 8080
  servlet:
    context-path: /

logging:
  level:
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/my-bank-demo-app.log
    max-size: 10MB
    max-history: 30
